<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>859e2914-9d22-41ab-9c48-7fb64eb70e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00f92884-1255-472d-9392-cc48e8a4cc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLogin</value>
      <webElementGuid>a9402d63-d0a0-4f5c-a951-0cd0ebae3a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6f373ed-76c7-4e81-bfe2-7e6efe6d80b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d1a0b97e-d039-4520-b413-c0e27ab9ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>c0adc188-9915-44a6-9788-12d838bc61d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLogin&quot;)</value>
      <webElementGuid>a37907bd-5e4b-4fb7-96b8-02cef3a4e763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnLogin']</value>
      <webElementGuid>4cf4c825-eac0-47d8-b92d-39ea9f440a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>63a00abc-27e1-4ac2-bb4d-45de136489c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnLogin' and @type = 'submit' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>d357dabe-b85e-4f1f-8034-7c1fa455f54a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
