<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LoginName</name>
   <tag></tag>
   <elementGuidId>dac012c1-ed98-4274-8680-7e28e14331e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4297f3c6-7fc6-4ca6-8cbc-107175fa7448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>832c0d8f-7ac6-49b2-b521-fdfbc2d84b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a64a6bd4-9d8c-44a9-b6ca-6bf799bea29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>966e32ef-7b5b-432f-811d-92b92cf8e38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LoginName field is required.</value>
      <webElementGuid>cf2faefd-8c3f-4544-800d-ff974fa4131f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginName</value>
      <webElementGuid>0ee8c770-187b-46ec-8236-cbd4d0422157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginName</value>
      <webElementGuid>fcf2076c-b43e-402d-8b7a-f79ce00f0991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>da5274fd-0896-4050-81ea-076bf8785368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bcf87d9-b8d9-4c9a-be9f-14c2bb7cdde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginName&quot;)</value>
      <webElementGuid>f3cc84be-d077-4890-9231-849ca4cea9b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginName']</value>
      <webElementGuid>86a6104e-784e-44f4-9bfd-50491e40c936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>94a03f0b-8369-441f-b4b4-51aef0b812cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LoginName' and @name = 'LoginName' and @placeholder = 'username' and @type = 'text']</value>
      <webElementGuid>cb0dbe7a-3265-4b74-8a75-a39b2deba9e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
