<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Videos</name>
   <tag></tag>
   <elementGuidId>055bd23c-8ff1-416f-b5af-db1bd79bae46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[64]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>32779fdb-a221-4ff2-a13c-3736d2f62a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dde766c0-6a83-4805-a38d-c7b8b8d3f31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-chip-cloud-chip-renderer</value>
      <webElementGuid>7a19bcd2-64bb-441c-ae93-a06cb79e81d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>2103d3a4-1dcb-47ad-a366-f439c09dbe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>421954b9-139f-4661-b811-df83e9e1211e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chip-bar&quot;)/yt-chip-cloud-renderer[@class=&quot;style-scope ytd-search-header-renderer&quot;]/div[@id=&quot;container&quot;]/div[@id=&quot;scroll-container&quot;]/iron-selector[@id=&quot;chips&quot;]/yt-chip-cloud-chip-renderer[@class=&quot;style-scope yt-chip-cloud-renderer&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>4ca9da00-d087-4520-845f-c50669fc39ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[64]</value>
      <webElementGuid>cc9eb0a1-1612-427d-a15e-852c1f4a4366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//iron-selector[@id='chips']/yt-chip-cloud-chip-renderer[3]/yt-formatted-string)[2]</value>
      <webElementGuid>e1ca9996-5dfc-43f3-9a27-1f26f38ed28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iron-selector/yt-chip-cloud-chip-renderer[3]/yt-formatted-string</value>
      <webElementGuid>14d97d49-f3e0-4e5f-8b0f-f32aee18ea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and @title = 'Videos' and (text() = 'Videos' or . = 'Videos')]</value>
      <webElementGuid>8f7abeff-52e1-4742-b6a4-44c792bf5629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
