<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Shorts</name>
   <tag></tag>
   <elementGuidId>8d5754eb-c092-4947-af9a-3ec40a658854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[63]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>6dea37be-42b7-47fd-8fb6-ed108d4b8818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b79b18d1-7660-4510-a6ad-8e6b22ba0b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-chip-cloud-chip-renderer</value>
      <webElementGuid>b66072dd-d5b9-4d3c-a7e6-56d92aaf0f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Shorts</value>
      <webElementGuid>b222a6c5-6224-492b-91cb-b84739292dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shorts</value>
      <webElementGuid>0c68946d-7e42-4c97-908e-d8efd6f95622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chip-bar&quot;)/yt-chip-cloud-renderer[@class=&quot;style-scope ytd-search-header-renderer&quot;]/div[@id=&quot;container&quot;]/div[@id=&quot;scroll-container&quot;]/iron-selector[@id=&quot;chips&quot;]/yt-chip-cloud-chip-renderer[@class=&quot;style-scope yt-chip-cloud-renderer&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>4ad33b1a-3cf8-40d5-a75b-96fff7917d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[63]</value>
      <webElementGuid>90f8fdaf-a1bd-453e-8cb9-7dceed0fe117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//iron-selector[@id='chips']/yt-chip-cloud-chip-renderer[2]/yt-formatted-string)[2]</value>
      <webElementGuid>18cfada2-a38a-4738-a991-b3b9165fdf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iron-selector/yt-chip-cloud-chip-renderer[2]/yt-formatted-string</value>
      <webElementGuid>ddb24060-eb30-466d-a28e-3eafa0f9dafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and @title = 'Shorts' and (text() = 'Shorts' or . = 'Shorts')]</value>
      <webElementGuid>825526a1-a7b2-44b2-a75c-1ada142ba1cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
